name: Release to Puppet Forge

on:
 push:
  tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish Puppet module
      uses: barnumbirr/action-forge-publish@v2.7.0
      env:
       FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
       REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
