---
.github/CONTRIBUTING.md:
  delete: true

.github/ISSUE_TEMPLATE.md:
  delete: true

.github/PULL_REQUEST_TEMPLATE.md:
  delete: true

.travis.yml:
  docker_sets:
    - set: debian8-64
    - set: debian9-64
    - set: debian10-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
    - set: centos6-64
    - set: centos7-64
  irc: false
  user: 'deric'
  secure: 'K3gfvfUtsZ4l6TTChG5jBLIB4j9ZG3zQECBCMI0ZcYiyiFYIihDtraO6sTf0qOcocRg5TpihBNJ8IpBPdDvd8bOrQCIWnSor2hP6NKA8J0XCDX5H4hmyieJhFCuGydaopia6rATEbj4TIOzMk8zPVc/lavg4yRkpwcxCy7UQVKc='

Rakefile:
  config.user: 'deric'

spec/spec_helper.rb:
  spec_overrides: "require 'spec_helper_local' if File.file?(File.join(File.dirname(__FILE__), 'spec_helper_local.rb'))"
