---
.travis.yml:
  use_litmus: true
  litmus:
    provision_list:
      - travis_deb
      - travis_el6
      - travis_el7
      - ---travis_el
  secure: "SDpX6jzritODonEQBqy9g0NbOmk2a9dBfAtZLrvHwM8BTpM2W0Y1daqzIbpzxFiqlNX+6r2GSq9SV70N0A9Ko/uPV9aG/XZx7MsBR9DNVjgqjJSl7+aF88VJfRpOv4PAyTM33JMx91nLFxM/ql61YX+2DXGXrhUkBsMZcdBgQnk="
spec/spec_helper.rb:
  mock_with: ':rspec'
